/* key.cpp --- 
 * 
 * Filename: key.cpp
 * Description: 
 * Author: Bryce
 * Maintainer: Adeel Bhutta
 * Created: Tue Sep  6 11:08:59 2016
 * Last-Updated: 01-10-2021
 *           By: Adeel Bhutta
 *     Update #: 0
 * Keywords: 
 * Compatibility: 
 * 
 */

/* Commentary: 
 * 
 * 
 * 
 */

/* Change log:
 * 
 * 
 */

/* Copyright (c) 2016 IUB
 * 
 * All rights reserved. 
 * 
 * Additional copyrights may follow 
 */

/* Code: */
#include <ncurses.h> 
#include "key.hpp"

int read_escape(int *read_char) {
  /*
  reads the key presses from keyboard by converting ANSI escape sequence
  generated by the arrow keys 
  */
  int c; 
  if ((c = getch()) == ERR) {
    // if there is an error (can't determine key), don't move
    return (NOCHAR);
  }
<<<<<<< HEAD
  // if the key is one of ANSI escpaes
  else if (c==0x1b) {
    // and if it is one of UP, DOWN, RIGHT, LEFT
    if ((c = getch()) == '[') {  
      c=getch();
=======
  else if (c == 0x1b) {
    if ((c = getch()) == '[') {
      c = getch();
>>>>>>> d6b687d7f30c058a8148e49195cef918fc04a1c7
      switch (c) {
      case 'A':
	return (UP);
	break;
      case 'B':
	return (DOWN);
	break;
      case 'C':
	return (RIGHT);
	break;
      case 'D':
	return (LEFT);
	break;
    case '20':
    return(SPACE);
  break;
      default: 
	return (BADESC);
      break;
      }
    }
  }
<<<<<<< HEAD
  else { 
=======
  else if(c == 0x20){
        return (SPACE);
  }
  else {
>>>>>>> d6b687d7f30c058a8148e49195cef918fc04a1c7
    *read_char = c;
    return (REGCHAR);
  }
}

/* key.cpp ends here */
